"use client"

import { FC } from "react"
import { getOwner } from "evolu"

type ShowMnemonicProps = {
  //
}

const ShowMnemonic: FC<ShowMnemonicProps> = () => {
  const onShowMnemonicClick = () => {
    getOwner().then((owner) => {
      alert(owner.mnemonic)
    })
  }

  return (
    <p>
      A Mnemonic is a strong and human-readable password generated by your
      device.
      <br />
      <button onClick={onShowMnemonicClick}>Show Mnemonic</button>
    </p>
  )
}

export default ShowMnemonic
